name: Going Backwards
author: [Brendon Ky](https://github.com/brendonky18)

description: |
You are going to be assigned a specific set of instructions, please do not refer to any of the other instruction sets.
Do not worry if you get stuck at any point, or are unable to complete the entire challenge, simply try to get as fas as possible based on the instructions and information provided. This is not meant to be an assessment of your knowledge, and you will not be impacted in any way regardless of how much you are able to complete. 

# Instructions
There is an FTP server exposed on port 2121. Inside this server there is a file titled `FLAG.txt` which contains the flag to be submitted. It should look something like `flag{ExampleFlag}`. The ftp server running is pyftp 0.8.4.5, which was actually available on Debian Release 5.0.4 from 2009-20010. A mirror of the source code is available at this [github repository](https://github.com/brendonky18/pyftpd-0.8.4.5_mirror).

If you are not familiar with FTP, it stands for *File Transferer Protocol*, and was designed to allow users to remotely access files stored on a server. 

Your task is to reverse engineer this program in order to discover a vulnerability which will allow you to capture the flag.

Reverse Engineering is the process of dismantling and examining a programs source code — sometimes even the assembly or raw binaries, which won't be necessary for this module — in order to understand what it does, how it works, and for our purposes, how it can be exploited.

# Additional Notes
Here are additional notes to assist you in solving the CTF.
- If you were born from January to April, please refer to the notes [here](https://github.com/brendonky18/Honors-Thesis.CTFs/blob/ctfd-integration/main/notes_0.md).
- If you were born from May to August, please refer to the notes [here](https://github.com/brendonky18/Honors-Thesis.CTFs/blob/ctfd-integration/main/notes_1.md).
- If you were born from September to December, please refer to the notes [here](https://github.com/brendonky18/Honors-Thesis.CTFs/blob/ctfd-integration/main/notes_2.md).

value: 100
category: Reverse Engineering

# administrative
container_name: going-backwards
