name: Docker Image CI

on:
  push:
    branches: [ main, going-backwards ]
  pull_request:
    branches: [ main, going-backwards ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./going-backwards
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ctfs:going-backwards
        build-args: FLAG=${{ secrets.GOING_BACKWARDS_FLAG }}